FORMAT: 1A
HOST: http://evently.io/

# evently

Evently is a simple API for creating, joining, and managing events

## Events Collection [/events]

### List All Events [GET]

+ Response 200 (application/json)

        [
            {
                "_id": "1q2w3e4r",
                "clientId":"9i8u7y6t",
                "secondId": "-erfdwe",
                "thirdId": "edc-ewq",
                "title": "Raiding the black zone,
                "slots": 10,
                "startTime": 123,
                "owner": {
                    "id": "cde3vfr4",
                    "name": "Riotgear66"
                },
                "participants": [],
                "webhook": "http://some-address.com/webhook"
            }
        ]

### Create a New Event [POST]

+ Request (application/json)

        {
            "clientId":"9i8u7y6t",
            "secondId": "-erfdwe",
            "thirdId": "edc-ewq",
            "title": "Raiding the black zone,
            "slots": 10,
            "startTime": 123,
            "owner": {
                "id": "cde3vfr4",
                "name": "Riotgear66"
            },
            "participants": [],
            "webhook": "http://some-address.com/webhook"
        }

+ Response 201 (application/json)


    + Body

            {
                "_id": "1q2w3e4r",
                "clientId":"9i8u7y6t",
                "secondId": "-erfdwe",
                "thirdId": "edc-ewq",
                "title": "Raiding the black zone,
                "slots": 10,
                "startTime": 123,
                "owner": {
                    "id": "cde3vfr4",
                    "name": "Riotgear66"
                },
                "participants": [],
                "webhook": "http://some-address.com/webhook"
            }