FORMAT: 1A
HOST: http://evently.io/

# evently

Evently is a simple API for creating, joining, and managing events

## Events [/events]

### List Events [GET]

+ Response 200 (application/json)

        [
            {
                "_id": "1q2w3e4r",
                "clientId":"9i8u7y6t",
                "secondId": "-erfdwe",
                "thirdId": "edc-ewq",
                "title": "Raiding the black zone,
                "slots": 10,
                "startTime": 123,
                "owner": {
                    "id": "cde3vfr4",
                    "name": "Riotgear66"
                },
                "participants": [],
                "webhook": "http://some-address.com/webhook"
            }
        ]

### Create Event [POST]

+ Request (application/json)

        {
            "clientId":"9i8u7y6t",
            "secondId": "-erfdwe",
            "thirdId": "edc-ewq",
            "title": "Raiding the black zone,
            "slots": 10,
            "startTime": 123,
            "owner": {
                "id": "cde3vfr4",
                "name": "Riotgear66"
            },
            "participants": [],
            "webhook": "http://some-address.com/webhook"
        }

+ Response 201 (application/json)


    + Body

            {
                "_id": "1q2w3e4r",
                "clientId":"9i8u7y6t",
                "secondId": "-erfdwe",
                "thirdId": "edc-ewq",
                "title": "Raiding the black zone,
                "slots": 10,
                "startTime": 123,
                "owner": {
                    "id": "cde3vfr4",
                    "name": "Riotgear66"
                },
                "participants": [],
                "webhook": "http://some-address.com/webhook"
            }
            
## Event [/events/{eventId}]

### Get Event [GET]
+ Response 200 (application/json)

### Update Event [PUT]
+ Response 200 (application/json)

### Remove Event [DELETE]
+ Response 200 (application/json)

## Participants [/events/{eventId}/participants]

### Add Participant [POST]
+ Response 200 (application/json)

### Remove Participant [DELETE]
+ Response 200 (application/json)