FORMAT: 1A
HOST: http://evently.io/

# evently

Evently is a simple API for creating, joining, and managing events

## Events [/events]

### List Events [GET]

+ Request

    + Headers
    
            Authorization: Bearer <token>

+ Response 200 (application/json)

        [
            {
                "_id": "1q2w3e4r",
                "secondId": "-erfdwe",
                "thirdId": "edc-ewq",
                "title": "Raiding the black zone",
                "slots": 10,
                "startTime": 123,
                "owner": {
                    "id": "cde3vfr4",
                    "name": "Riotgear66"
                },
                "participants": [],
                "webhook": "http://some-address.com/webhook"
            },
            {
                "_id": "w2q1r4e3",
                "clientId":"715209",
                "secondId": null,
                "thirdId": null,
                "title": "Creating 2nd event",
                "slots": 3,
                "startTime": 852963741,
                "owner": {
                    "id": "902517",
                    "name": "Tom"
                },
                "participants": [],
                "webhook": "http://some-address.com/webhook"
            }
        ]

### Create Event [POST]
        
+ Request (application/json)
    + Headers
    
            Authorization: Bearer <token>
    
    + Body
    
            {
                "secondId": "-erfdwe",
                "thirdId": "edc-ewq",
                "title": "Raiding the black zone",
                "slots": 10,
                "startTime": 123,
                "owner": {
                    "id": "cde3vfr4",
                    "name": "Riotgear66"
                },
                "webhook": "http://some-address.com/webhook"
            }
    
        
    + Schema

            {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "title": "Event",
                "description": "Event structure and properties",
                "type": "object",
                "properties": {
                    "secondId": {
                      "type": "string"
                    },
                    "thirdId": {
                      "type": "string"
                    },
                    "title": {
                      "type": "string"
                    },
                    "slots": {
                      "type": "number"
                    },
                    "startTime": {
                      "type": "number"
                    },
                    "owner": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        }
                      }
                    },
                    "webhoook": {
                      "type": "string"
                    }
              }
            }

+ Response 201 (application/json)
    
        {
            "_id": "1q2w3e4r",
            "secondId": "-erfdwe",
            "thirdId": "edc-ewq",
            "title": "Raiding the black zone",
            "slots": 10,
            "startTime": 123,
            "owner": {
                "id": "cde3vfr4",
                "name": "Riotgear66"
            },
            "participants": [],
            "webhook": "http://some-address.com/webhook"
        }
            
## Event [/events/{event_id}]
+ Parameters
    + event_id (string) - ID of the requested event
    
### Get Event [GET]
+ Request

    + Headers
    
            Authorization: Bearer <token>
            
+ Response 200 (application/json)
    
            {
                "_id": "1q2w3e4r",
                "secondId": "-erfdwe",
                "thirdId": "edc-ewq",
                "title": "Raiding the black zone",
                "slots": 10,
                "startTime": 123,
                "owner": {
                    "id": "cde3vfr4",
                    "name": "Riotgear66"
                },
                "participants": [],
                "webhook": "http://some-address.com/webhook"
            }

### Update Event [PUT]
+ Request (application/json)
    
    + Headers
    
            Authorization: Bearer <token>
    
    + Body
    
            {
                "secondId": "-erfdwe",
                "thirdId": "edc-ewq",
                "title": "Raiding the black zone",
                "slots": 10,
                "startTime": 123,
                "owner": {
                    "id": "cde3vfr4",
                    "name": "Riotgear66"
                },
                "webhook": "http://some-address.com/webhook"
            }
    
        
    + Schema

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "secondId": {
                  "type": "string"
                },
                "thirdId": {
                  "type": "string"
                },
                "title": {
                  "type": "string"
                },
                "slots": {
                  "type": "number"
                },
                "startTime": {
                  "type": "number"
                },
                "owner": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    }
                  }
                },
                "webhoook": {
                  "type": "string"
                }
              }
            }
+ Response 201 (application/json)
    
        {
            "_id": "1q2w3e4r",
            "secondId": "-erfdwe",
            "thirdId": "edc-ewq",
            "title": "Raiding the black zone",
            "slots": 10,
            "startTime": 123,
            "owner": {
                "id": "cde3vfr4",
                "name": "Riotgear66"
            },
            "participants": [],
            "webhook": "http://some-address.com/webhook"
        }
        
### Remove Event [DELETE]
+ Request

    + Headers
    
            Authorization: Bearer <token>
            
+ Response 204 (application/json)
    
## Participants [/events/{eventId}/participants]

### Add Participant [POST]
+ Request (application/json)

    + Headers
    
            Authorization: Bearer <token>
    
    + Body
        
            {
                "id": "1q2w3e4r",
                "name": "iFatebringer"
            }
        
+ Response 201 (application/json)
    
        {
            "_id": "1q2w3e4r",
            "secondId": "-erfdwe",
            "thirdId": "edc-ewq",
            "title": "Raiding the black zone",
            "slots": 10,
            "startTime": 123,
            "owner": {
                "id": "cde3vfr4",
                "name": "Riotgear66"
            },
            "participants": [],
            "webhook": "http://some-address.com/webhook"
        }

## Participant [/events/{eventId}/participants/{participantId}]

### Remove Participant [DELETE]
+ Request (application/json)

    + Headers
    
            Authorization: Bearer <token>
            
+ Response 204

## Data Structures

### Event
    {
        "title": "Event",
        "$schema": "http://json-schema.org/draft-04/schema#",
        "description": "Event structure and properties",
        "type": "object",
        "properties": {
            "secondId": {
              "type": "string"
            },
            "thirdId": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "slots": {
              "type": "number"
            },
            "startTime": {
              "type": "number"
            },
            "owner": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                }
              }
            },
            "webhoook": {
              "type": "string"
            }
      }
    }